### ISSUE TITLE
View for outputs

### ISSUE THREAD

**Issue by Dgadavin** [camptocamp/terraboard#50] opened 2018-10-11 12:51 UTC
It would be very good if terraform outputs also has they own view. I see that the contributor is no longer develop this beautiful tool but maybe some one else can do this. 
Thanks a lot.

**Comment by raphink** [comment] 2018-10-12 06:29
@Dgadavin I haven't committed for a long time because I've had no need for new features and no requests either, but I'm definitely open to contributions.

I've thought of integrating outputs. The problem is that they are not stored anywhere by Terraform, so this requires to either push to the tool or patch Terraform to store the outputs somewhere.

**Comment by Dgadavin** [comment] 2018-10-12 07:06
@raphink As far as I know outputs stored in tfstate. Something like this. https://github.com/mdb/terraform-example/blob/master/terraform/terraform.tfstate#L9

**Comment by raphink** [comment] 2018-10-12 07:50
Ah, this might be new then. They weren't stored in the state a year ago afaik.

**Comment by raphink** [comment] 2018-10-31 16:36
@Dgadavin 	I started working on https://github.com/camptocamp/terraboard/pull/51

**Comment by Dgadavin** [comment] 2018-11-05 09:16
Looks good

**Closed** 2021-02-24 09:36 UTC
Labels: enhancement
